name: Bug Issue
description: File a bug issue
title: "[主题 issue] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        ## 问题描述
  - type: textarea
    id: description-auth
    attributes:
      label: \n
      value: "## 问题描述\n- owner: \n- cooperator: \n- reviewer: \n\n"
  - type: textarea
    id: description-content
    attributes:
      label: 内容
  - type: markdown
    attributes:
      value: |
        ## 解决方案
  - type: textarea
    id: design-auth
    attributes:
      label: \n
      value: "## 解决方案\n- owner: \n- cooperator: \n- reviewer: \n\n"
  - type: textarea
    id: design-content
    attributes:
      label: 方案和链接
  - type: markdown
    attributes:
      value: |
        ## 开发
  - type: textarea
    id: development-auth
    attributes:
      label: \n
      value: "## 开发\n- owner: \n- cooperator: \n- reviewer: \n\n"
  - type: textarea
    id: development-content
    attributes:
      label: PR 列表
      value: "- \n"
  - type: markdown
    attributes:
      value: |
        ## 测试
  - type: textarea
    id: test-auth
    attributes:
      label: \n
      value: "## 测试\n- owner: \n- cooperator: \n- reviewer: \n\n"
  - type: textarea
    id: test-content
    attributes:
      label: 测试反馈
  - type: markdown
    attributes:
      value: |
        ## 发版
  - type: textarea
    id: release-auth
    attributes:
      label: \n
      value: "## 发版\n- owner: \n- cooperator: \n- reviewer: \n\n"
  - type: textarea
    id: release-content
    attributes:
      label: 发版反馈
