name: Bug Issue
description: File a bug issue
title: "[主题 issue] "
labels: ["bug", "问题描述"]
body:
  - type: textarea
    id: problem
    attributes:
      label: 问题描述
      value: "owner: \ncooperator: \n"
  - type: textarea
    id: plan
    attributes:
      label: 解决方案
      value: "owner: \ncooperator: \n"
  - type: textarea
    id: development
    attributes:
      label: 开发
      value: "owner: \ncooperator: \n"
  - type: textarea
    id: test
    attributes:
      label: 测试
      value: "owner: \ncooperator: \n"
  - type: textarea
    id: issue
    attributes:
      label: 发版
      value: "owner: \ncooperator: \n"
