name: Bug Issue
description: File a bug issue
title: "[主题 issue] "
labels: "bug"
body:
  - type: textarea
    id: problem
    attributes:
      label: 问题描述
  - type: textarea
    id: plan
    attributes:
      label: 解决方案
  - type: textarea
    id: development
    attributes:
      label: 开发
  - type: textarea
    id: test
    attributes:
      label: 测试
  - type: textarea
    id: issue
    attributes:
      label: 发版
      
