name: Bug Issue
description: File a bug issue
title: "[主题 issue] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        ## 问题描述
  - type: input
    id: description-owner
    attributes:
      label: owner
    validations:
      required: true
  - type: input
    id: description-cooperator
    attributes:
      label: cooperator
    validations:
      required: false
  - type: input
    id: description-reviewer
    attributes:
      label: reviewer
    validations:
      required: true
  - type: textarea
    id: plan
    attributes:
      label: 解决方案
      value: "- owner: \n- cooperator: \n- reviewer: \n\n"
  - type: textarea
    id: development
    attributes:
      label: 开发
      value: "- owner: \n- cooperator: \n- reviewer: \n\n"
  - type: textarea
    id: test
    attributes:
      label: 测试
      value: "- owner: \n- cooperator: \n- reviewer: \n\n"
  - type: textarea
    id: issue
    attributes:
      label: 发版
      value: "- owner: \n- cooperator: \n- reviewer: \n\n"
  - type: textarea
    id: link
    attributes:
      label: 相关链接
