name: Chore Issue
description: File a chore issue
title: "[主题 issue] "
labels: ["chore", "task"]
body:
body:
  - type: textarea
    id: description-content
    attributes:
      label:  背景描述
  - type: textarea
    id: description-auth
    attributes:
      label: 授权
      value: "* owner: \n* cooperator: \n* reviewer: \n\n---"
  - type: textarea
    id: design-content
    attributes:
      label: 方案设计
      value: "\n\n\n#### 资料链接\n* "
  - type: textarea
    id: design-auth
    attributes:
      label: 授权
      value: "* owner: \n* cooperator: \n* reviewer: \n\n---"
  - type: textarea
    id: release-content
    attributes:
      label: 方案落地
      value: "#### 落地反馈\n* "
  - type: textarea
    id: release-auth
    attributes:
      label: 授权
      value: "* owner: \n* cooperator: \n* reviewer: \n\n---"
