name: Feature Issue
description: File a feature issue
title: "[主题 issue] "
labels: ["feature"]
body:
body:
  - type: textarea
    id: description-content
    attributes:
      label:  需求描述
  - type: textarea
    id: description-auth
    attributes:
      label: 授权
      value: "* owner: \n* cooperator: \n* reviewer: \n\n---"
  - type: textarea
    id: design-content
    attributes:
      label: 方案设计
      value: "\n\n\n#### 资料链接\n* "
  - type: textarea
    id: design-auth
    attributes:
      label: 授权
      value: "* owner: \n* cooperator: \n* reviewer: \n\n---"
  - type: textarea
    id: development-content
    attributes:
      label: 开发
      value: "#### 开发 PR 列表\n* "
  - type: textarea
    id: development-auth
    attributes:
      label: 授权
      value: "* owner: \n* cooperator: \n* reviewer: \n\n---"
  - type: textarea
    id: test-content
    attributes:
      label: 测试
      value: "#### 测试反馈\n* "
  - type: textarea
    id: test-auth
    attributes:
      label: 授权
      value: "* owner: \n* cooperator: \n* reviewer: \n\n---"
  - type: textarea
    id: release-content
    attributes:
      label: 发版
      value: "#### 发版 PR\n* "
  - type: textarea
    id: release-auth
    attributes:
      label: 授权
      value: "* owner: \n* cooperator: \n* reviewer: \n\n---"
