name: Release Issue
description: File a release issue
title: "[主题 issue] "
labels: ["release"]
body:
  - type: textarea
    id: description
    attributes:
      label: 发版内容
      value: "- owner: \n- cooperator: \n- reviewer: \n\n#### Bug fix\n* \n\n#### Features\n* \n\n#### Maintain\n* \n"
  - type: textarea
    id: development
    attributes:
      label: 开发
      value: "- owner: \n- cooperator: \n- reviewer: \n\n#### PR list\n* \n\n"
  - type: textarea
    id: test
    attributes:
      label: 测试
      value: "- owner: \n- cooperator: \n- reviewer: \n\n"
  - type: textarea
    id: issue
    attributes:
      label: 发版
      value: "- owner: \n- cooperator: \n- reviewer: \n\n"
  - type: textarea
    id: link
    attributes:
      label: 相关链接
