name: Assign reviewers based on asignees

on: 
  issues:
    type: [assigned]
    
jobs:
  must-assign-rev-chaos:
    runs-on: ubuntu-latest
    steps:
      - name: print-bug-issue-reviewer
        if: (startsWith(github.event.issue.title, '[主题 issue]') && contains(github.event.issue.labels.*.name, 'bug') && !contains(github.event.issue.labels.*.name, '解决方案') && toJson(github.event.issue.assignees) != '[]')
        uses: actions-cool/issues-helper@v2
        with:
          actions: 'create-comment'
          issue-number: ${{ github.event.issue.number }}
          body: |
            已指定 @${{ join(github.event.issue.assignees.*.login, ', @') }} 作为 “问题描述” 的 reviewers！issue_state: ${{ github.event.issue.state }}
      - name: must-assign-rev-chaos
        if: (startsWith(github.event.issue.title, '[主题 issue]') && toJson(github.event.issue.assignees) != '[]' && !contains(github.event.issue.assignees.*.login, 'rev-chaos'))
        uses: actions-cool/issues-helper@v2
        with:
          actions: 'create-comment'
          issue-number: ${{ github.event.issue.number }}
          body: |
            @${{ github.event.issue.user.login }}，必须指定 rev-chaos 作为 reviewers！
