name: Create Issue

on:
  issues:
    types: [opened]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  check-issue:
    runs-on: ubuntu-latest
    steps:
      - name: check title
        if: (contains(github.event.issue.title, '[主题 issue]') == false)
        uses: actions-cool/issues-helper@v2
        with:
          actions: 'create-comment,add-labels,close-issue'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            @${{ github.event.issue.user.login }}，issue 的 title 必须以 '[主题 issue]' 为前缀，谢谢配合！
      - name: assign new issue to project
        uses: srggrs/assign-one-project-github-action@1.2.1
        with:
          project: 'https://github.com/rev-chaos/demo-script/projects/1'
          column_name: 'todo'
