name: Create Issue

on:
  issues:
    types: [opened]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  assign-project:
    runs-on: ubuntu-latest
    steps:
      - name: assign new subject issue to project
        if: contains(github.event.issue.labels.*.name, 'task')
        uses: srggrs/assign-one-project-github-action@1.2.1
        with:
          project: 'https://github.com/rev-chaos/demo-script/projects/1'
          column_name: 'Uncertain & Others'
