name: Create Issue

on:
  issues:
    types: [opened]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  check-bug-issue:
    runs-on: ubuntu-latest
    steps:
      - name: check bug issue title
        if: (contains(github.event.issue.title, '[主题 issue]') && contains(github.event.issue.labels.*.name, 'bug'))
        uses: actions-cool/issues-helper@v2
        with:
          actions: 'create-comment'
          issue-number: ${{ github.event.issue.number }}
          body: |
            @${{ github.event.issue.user.login }}，请指定 assignees 以确定 “问题描述” 的 reviewers！
      - name: assign new issue to project
        uses: srggrs/assign-one-project-github-action@1.2.1
        with:
          project: 'https://github.com/rev-chaos/demo-script/projects/1'
          column_name: 'todo'
