name: Move

on: 
  issue_comment:
    type: [created]
    
jobs:
  move-subject-issue:
    runs-on: ubuntu-latest
    if: startsWith(github.event.issue.title, '[主题 issue]') && github.event.issue.user.login == 'rev-chaos' && contains(github.event.comment.body, '\approve')
    steps:
      - name: move bug description
        if: contains(github.event.issue.labels.*.name, 'bug') && !contains(github.event.issue.labels.*.name, '问题描述')
        uses: alex-page/github-project-automation-plus@v0.8.1
        with:
          project: '任务面板'
          column: 'Description Approved'
          repo-token: ${{ secrets.GHPROJECT_TOKEN }}
