name: Approve

on: 
  issue_comment:
    type: [created]
    
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
  
jobs:
  move-project:
    runs-on: ubuntu-latest
    if: startsWith(github.event.issue.title, '[主题 issue]') && github.event.issue.user.login == 'rev-chaos' && contains(github.event.comment.body, '\approve')
    steps:
      - uses: alex-page/github-project-automation-plus@v0.8.0
        with:
          project: Task
          column: Description Approved
          repo-token: ${{ secrets.GITHUB_TOKEN }}
