name: Approve

on: 
  issues:
    type: [update]
    
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
  
jobs:
  move-project:
    runs-on: ubuntu-latest
    steps:
      - name: approve bug description
        if: contains(github.event.issue.labels.*.name, 'bug') && !contains(github.event.issue.labels.*.name, '问题描述')
        uses: alex-page/github-project-automation-plus@v0.7.0
        with:
          project: '任务面板'
          column: 'Description Approved'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
