name: Approve

on: 
  issue_comment:
    type: [created]
    
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
  
jobs:
  move-project:
    runs-on: ubuntu-latest
    if: startsWith(github.event.issue.title, '[主题 issue]') && github.event.issue.user.login == 'rev-chaos' && contains(github.event.comment.body, '\approve')
    steps:
      - name: approve bug description
        if: contains(github.event.issue.labels.*.name, 'bug') && !contains(github.event.issue.labels.*.name, '问题描述')
        uses: alex-page/github-project-automation-plus@v0.8.0
        with:
          project: 'https://github.com/rev-chaos/demo-script/projects/1'
          column: 'Description Approved'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: approve bug design
        if: contains(github.event.issue.labels.*.name, 'bug') && contains(github.event.issue.labels.*.name, '问题描述') && !contains(github.event.issue.labels.*.name, '方案设计')
        uses: srggrs/assign-one-project-github-action@1.2.1
        with:
          project: 'https://github.com/rev-chaos/demo-script/projects/1'
          column_name: 'Design Approved'
      - name: approve bug development
        if: contains(github.event.issue.labels.*.name, 'bug') && contains(github.event.issue.labels.*.name, '解决方案') && !contains(github.event.issue.labels.*.name, '开发')
        uses: srggrs/assign-one-project-github-action@1.2.1
        with:
          project: 'https://github.com/rev-chaos/demo-script/projects/1'
          column_name: 'Development Approved'
      - name: approve bug test
        if: contains(github.event.issue.labels.*.name, 'bug') && contains(github.event.issue.labels.*.name, '开发') && !contains(github.event.issue.labels.*.name, '测试')
        uses: srggrs/assign-one-project-github-action@1.2.1
        with:
          project: 'https://github.com/rev-chaos/demo-script/projects/1'
          column_name: 'Test Approved'
      - name: approve bug release
        if: contains(github.event.issue.labels.*.name, 'bug') && contains(github.event.issue.labels.*.name, '测试') && !contains(github.event.issue.labels.*.name, '发版')
        uses: srggrs/assign-one-project-github-action@1.2.1
        with:
          project: 'https://github.com/rev-chaos/demo-script/projects/1'
          column_name: 'Deploy & Release Approved'
      - name: approve feature description
        if: contains(github.event.issue.labels.*.name, 'feature') && !contains(github.event.issue.labels.*.name, '需求描述')
        uses: srggrs/assign-one-project-github-action@1.2.1
        with:
          project: 'https://github.com/rev-chaos/demo-script/projects/1'
          column_name: 'Description Approved'
      - name: approve feature design
        if: contains(github.event.issue.labels.*.name, 'feature') && contains(github.event.issue.labels.*.name, '需求描述') && !contains(github.event.issue.labels.*.name, '方案设计')
        uses: srggrs/assign-one-project-github-action@1.2.1
        with:
          project: 'https://github.com/rev-chaos/demo-script/projects/1'
          column_name: 'Design Approved'
      - name: approve feature development
        if: contains(github.event.issue.labels.*.name, 'feature') && contains(github.event.issue.labels.*.name, '方案设计') && !contains(github.event.issue.labels.*.name, '开发')
        uses: srggrs/assign-one-project-github-action@1.2.1
        with:
          project: 'https://github.com/rev-chaos/demo-script/projects/1'
          column_name: 'Development Approved'
      - name: approve feature test
        if: contains(github.event.issue.labels.*.name, 'feature') && contains(github.event.issue.labels.*.name, '开发') && !contains(github.event.issue.labels.*.name, '测试')
        uses: srggrs/assign-one-project-github-action@1.2.1
        with:
          project: 'https://github.com/rev-chaos/demo-script/projects/1'
          column_name: 'Test Approved'
      - name: approve feature release
        if: contains(github.event.issue.labels.*.name, 'feature') && contains(github.event.issue.labels.*.name, '测试') && !contains(github.event.issue.labels.*.name, '发版')
        uses: srggrs/assign-one-project-github-action@1.2.1
        with:
          project: 'https://github.com/rev-chaos/demo-script/projects/1'
          column_name: 'Deploy & Release Approved'
      - name: approve release description
        if: contains(github.event.issue.labels.*.name, 'release') && !contains(github.event.issue.labels.*.name, '发版目标')
        uses: srggrs/assign-one-project-github-action@1.2.1
        with:
          project: 'https://github.com/rev-chaos/demo-script/projects/1'
          column_name: 'Description Approved'
      - name: approve release development
        if: contains(github.event.issue.labels.*.name, 'release') && contains(github.event.issue.labels.*.name, '发版目标') && !contains(github.event.issue.labels.*.name, '开发')
        uses: srggrs/assign-one-project-github-action@1.2.1
        with:
          project: 'https://github.com/rev-chaos/demo-script/projects/1'
          column_name: 'Development Approved'
      - name: approve release test
        if: contains(github.event.issue.labels.*.name, 'release') && contains(github.event.issue.labels.*.name, '开发') && !contains(github.event.issue.labels.*.name, '测试')
        uses: srggrs/assign-one-project-github-action@1.2.1
        with:
          project: 'https://github.com/rev-chaos/demo-script/projects/1'
          column_name: 'Test Approved'
      - name: approve release release
        if: contains(github.event.issue.labels.*.name, 'release') && contains(github.event.issue.labels.*.name, '测试') && !contains(github.event.issue.labels.*.name, '发版')
        uses: srggrs/assign-one-project-github-action@1.2.1
        with:
          project: 'https://github.com/rev-chaos/demo-script/projects/1'
          column_name: 'Deploy & Release Approved'
      - name: approve chore description
        if: contains(github.event.issue.labels.*.name, 'chore') && !contains(github.event.issue.labels.*.name, '背景描述')
        uses: srggrs/assign-one-project-github-action@1.2.1
        with:
          project: 'https://github.com/rev-chaos/demo-script/projects/1'
          column_name: 'Description Approved'
      - name: approve chore development
        if: contains(github.event.issue.labels.*.name, 'chore') && contains(github.event.issue.labels.*.name, '背景描述') && !contains(github.event.issue.labels.*.name, '方案设计')
        uses: srggrs/assign-one-project-github-action@1.2.1
        with:
          project: 'https://github.com/rev-chaos/demo-script/projects/1'
          column_name: 'Design Approved'
      - name: approve chore test
        if: contains(github.event.issue.labels.*.name, 'chore') && contains(github.event.issue.labels.*.name, '方案设计') && !contains(github.event.issue.labels.*.name, '方案落地')
        uses: srggrs/assign-one-project-github-action@1.2.1
        with:
          project: 'https://github.com/rev-chaos/demo-script/projects/1'
          column_name: 'Deploy & Release Approved'
