name: Approve

on: 
  issue_comment:
    type: [created]
    
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
  
jobs:
  move-project:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.8.0
        with:
          project: 任务面板
          column: Description Approved
          repo-token: ${{ secrets.GHPROJECT_TOKEN }}
