name: Approve

on: 
  issue_comment:
    type: [created]
    
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
  
jobs:
  move-project:
    runs-on: ubuntu-latest
    if: startsWith(github.event.issue.title, '[主题 issue]') && github.event.issue.user.login == 'rev-chaos' && contains(github.event.comment.body, '\approve')
    steps:
      - name: approve bug description
        if: contains(github.event.issue.labels.*.name, 'bug') && !contains(github.event.issue.labels.*.name, '问题描述')
        uses: alex-page/github-project-automation-plus@be108970955040d35dd6d053c3aff3faaf678026
        with:
          project: '任务面板'
          column: 'Description Approved'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
