name: Approve

on: 
  issue_comment:
    type: [created]
    
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
  
jobs:
  move-project:
    runs-on: ubuntu-latest
    steps:
      - name: approve bug description
        if: contains(github.event.issue.labels.*.name, 'bug') && !contains(github.event.issue.labels.*.name, '问题描述')
        uses: srggrs/assign-one-project-github-action@1.2.1
        with:
          project: 'https://github.com/rev-chaos/demo-script/projects/1'
          column_name: 'Description Approved'
